version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # Management
      - "5672:5672" # AMQP
    volumes:
      - ./rabbit.definitions.json:/tmp/rabbit.definitions.json:ro
      - rabbit_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/tmp/rabbit.definitions.json"

volumes:
  rabbit_data:
